### ISSUE TITLE
_theme.scss

### ISSUE THREAD

**Issue by WhatsNewSaes** [whatsnewsaes/Boneless#19]
It would be cool to have a theme sass file, that you can change a few variables that will be throughout all the other sass files for quick theming.

**Comment by benhinchley** [comment]
Yeah that is a pretty decent idea, especially for those just wanting to change colours and fonts and not a lot else

**Comment by diagramatics** [comment]
If we're talking about Sass, I don't think we should. Sass users have an easier way to do this—just @import the main entry file and override as necessary.

**Comment by hamaluik** [comment]
@diagramatics in that case, perhaps merely including instructions for that would be enough?

**Comment by benhinchley** [comment]
@diagramatics @FuzzyWuzzie I have been thinking this about a bit more lately, and I do have to agree with @diagramatics that in is unnecessary to have a separate file, but as @FuzzyWuzzie some documentation on how to customise

**Comment by benhinchley** [comment]
I am going to close this, as I think we have come to a decent conclusion. If anyone wants to add to it feel free to open it back up again. Also if anyone wants to add that documentation feel free to PR the changes
