### ISSUE TITLE
Change build system from grunt to gulp??

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#2]
I personally wouldn't mind seeing the build system change from grunt to gulp, I find it much more intuitive and streamlined, and also a bit quicker depending on the project.

**Comment by WhatsNewSaes** [comment]
I've never used gulp, but I've heard great things. I'm down to try it out if you want to change it.

**Comment by benhinchley** [comment]
Yep happy to change it, will work on it and create a PR shortly

**Comment by benhinchley** [comment]
I am going to close this issue as I have made the changes in PR #5
