### ISSUE TITLE
Improve / Polish buttons

### ISSUE THREAD

**Issue by WhatsNewSaes** [whatsnewsaes/Boneless#20]
@benhinchley I know you're currently working on a pretty fantastic mixin for these.

I would just say that we should include the following selectors
`button, input[type="submit", input[type="reset"], input[type="button"]`

**Comment by benhinchley** [comment]
Yep currently refactoring entire mixin, so that it is more robust, and will allow the styling on those elements

**Comment by benhinchley** [comment]
Have added support for all elements types, and for the ability to change the border-radius on the button, currently working on more styles/types additional to the current border & solid types

**Comment by benhinchley** [comment]
#25 just linking the two

**Comment by benhinchley** [comment]
going to close this and move the discussion over to #25
