### ISSUE TITLE
Improve / Polish Typography

### ISSUE THREAD

**Issue by WhatsNewSaes** [whatsnewsaes/Boneless#21]
Move to em based system, based on some sort of typographic scale

**Comment by benhinchley** [comment]
@whatsnewsaes to do you want to work on this??

**Comment by benhinchley** [comment]
Began working on this, taking into account @whatsnewsaes previous work on this PR #38

**Comment by benhinchley** [comment]
Moving conversation to PR #38 so am closing this issue
