### ISSUE TITLE
Change from Sassdoc to something else??

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#24]
after some thought about this project, and realising the whole thing isn't going to be Sass mixins, functions, placeholders etc. Think it might be better to be using KSS or something like it, for our documentation generation, they provide better/support in general for plain old css things, as well as Sass specific things like mixins

**Comment by benhinchley** [comment]
Have been looking at some of the other options, and have tried out a few of them, and so far haven't found anything that works as well as sassdoc

**Comment by WhatsNewSaes** [comment]
Sassdoc just looked so freaking complex. maybe i just need the run down on it.

**Comment by benhinchley** [comment]
it's not overly complicated, works the same as most other doc gen tools like yuidoc, the annotations do take a bit of getting used to and I pretty much have the Sassdoc website open whenever I am adding documentation to something. 

This does bring up issue #15 Think the information about how to write and update/extend the documentation, needs a lot more work, might start the wiki and start making all of that information a lot simpler 

I am also not entirely sure that my issues with Sassdoc are actually valid issues, like for the most part, we don't really need to be documenting the css that we write as, it is usually just written to implement the mixins/ functions etc, though seeing this is project is still quite new, that is probably going to change

**Comment by benhinchley** [comment]
I am happy with Sassdoc for now, will close this. We can reopen if we find that it is not suitable anymore
