### ISSUE TITLE
Update the grid

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#3]
I was thinking about the grid, and whether we should upgrade the grid to be a bit more robust and have bootstrap/foundation style grid with classes for the different ones like sm-4 for 4 columns in small grid etc.

**Comment by WhatsNewSaes** [comment]
agreed. Grid needs to be much more robust. I personally like foundation's grid, but either way i think it would be good to include:
- Small settings
- Medium settings
- Large settings
- Offsets
- Nesting

**Comment by benhinchley** [comment]
Yeah that is true, been using the foundation grid a bit recently, it is quite nice, in terms of ease of use and robustness.

**Comment by benhinchley** [comment]
Do we want to base the grid off the skeleton grid?? or just write a whole new grid?

**Comment by benhinchley** [comment]
I am going to close this one now, seeing the grid is now in.
