### ISSUE TITLE
Register on Bower

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#35]
So as brought up by @diagramatics PR #34 , there is currently already a package register on bower under the name `boneless`, [rish/boneless](https://github.com/rish/boneless), and it appears as though the owner is just name-squatting.

**Comment by diagramatics** [comment]
Not necessarily only name-squatting, but just registering the name before getting a working version to publish with. That said, I'm not certain if package names are case-sensitive but we can try and register Boneless with a capital B for now, name confusion and all.

The README.md should be updated to show the Bower installation procedures as `bower install whatsnewsaes/Boneless` for now before this issue gets closed.

**Comment by WhatsNewSaes** [comment]
We could go with `boneless-framework` or `boneless-css`

Also, I believe bower requires all names to be lowercase

**Comment by benhinchley** [comment]
I'd suggest against `boneless-css` as this isn't css but Sass, Would it be worthwhile sending rish a message to see if we can get the name off them????

**Comment by diagramatics** [comment]
That would be best if the name stays later on.

**Comment by diagramatics** [comment]
And this reminds me, I have to question about the use of -D or --save-dev as opposed to --save. Bower's devDependencies are rarely used since the packages are going to be bundled on the finished site later on. Any specific reason about this?

**Comment by benhinchley** [comment]
I use `-D` as apposed to `--save` with my Sass libraries, as imho there isn't any point of bundling up my sass source code, together with my finished site that I deploy to the server. To me Sass is a development dependency, not a dependency of the project when actually running on the web. So that is kind of the reasoning behind it.

as an example my `bower.json` files often look like this

``` json
  "devDependencies": {
    "breakpoint-sass": "~2.5.0",
    "skeleton-scss": "*"
  },
  "dependencies": {
    "angular": "~1.3.15",
    "angularfire": "~1.0.0"
  }
```

as `angular` & `angularfire` are "true" dependancies of the project (ie project doesn't work without them), and needs to be moved with everything else to the server, but `skeleton-scss` & `breakpoint-sass` are just things I use in development, and don't need to be brought across to the server. 

Hopefully that explains my reasoning, behind the use of `-D`.

**Comment by diagramatics** [comment]
Ah, fair enough. I rarely see people using devDependencies in Bower, but that seems like a valid reasoning.

**Comment by benhinchley** [comment]
Yeah I don't see it happening a lot either, and I don't really get why (it's not used that is).

**Comment by diagramatics** [comment]
Ah, one more thing about the Bower file. We need a "main" on bower.json to define the main files to use from Boneless, which would be both boneless.scss and the mixins file?

**Comment by benhinchley** [comment]
@diagramatics have made some updates to the bower.json file in this commit 6971561ec24a599e82ee803cb4838ffb45099988 for now have only added `boneless.scss` to the `"main"` tag.

**Comment by benhinchley** [comment]
This is now registered on bower as of commit 7ebf295d66cbf1f9c35bbe1e8d8d96f312a565c0 and can be installed through `bower install boneless-framework`
