### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by dashed** [whatsnewsaes/Boneless#39]
Doesn't exist yet: https://www.npmjs.com/package/Boneless

Might I suggest adding this project to npm?

**Comment by benhinchley** [comment]
Yeah @Dashed What are the benefits of front-end packages like this on NPM?? Never really used it for css type packages

**Comment by dashed** [comment]
This is useful for those that may prefer to consume npm modules, especially for users that use bundlers such as browserify or webpack.

**Comment by benhinchley** [comment]
Yeah fair enough, i'll try do it tonight, and update the readme to replicate

**Comment by benhinchley** [comment]
@Dashed you can install through npm as of this commit 110adeaa187cedc98c4620fff763800a2ffc1f7c

**Comment by dashed** [comment]
@benhinchley Thanks! :+1:
