### ISSUE TITLE
Thinking about creating an org

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#42]
As the sole maintainer of this, and cause I am not putting as much time into this as I would like to, I have been thinking about creating a `Boneless` org to help in the maintainence and development of boneless. 

Are there people who would be interested in helping me maintain and develop boneless?? If so I'll create an org and get a few people on the core team, can also add you to a slack team that me and @WhatsNewSaes had when we started this

**Comment by hamaluik** [comment]
I would be interested!

**Comment by JayWIlsonJr** [comment]
I would be interested also!

**Comment by benhinchley** [comment]
@FuzzyWuzzie @JayWIlsonJr I will organise creating the org this week and invite you guys later

**Comment by JayWIlsonJr** [comment]
ok, sounds good. Thanks for the update.

**Comment by benhinchley** [comment]
I am going to close this, Ill be in contact with you both in the next week or two
