### ISSUE TITLE
Semantic grid vs Grid Classes

### ISSUE THREAD

**Issue by benhinchley** [whatsnewsaes/Boneless#7]
What are peoples opinions on the use of grid classes like skeletons `one column`, `container`, `row` classes compared defining their grid semantically within their css, leaving their html as clean as possible, like [profound grid](http://www.profoundgrid.com/) is doing?

**Comment by WhatsNewSaes** [comment]
I like setting on the html tag rather than in the css. I'd think larger projects could potentially bloat your css when using profound grid's method. I like the direction our grid is going. I'll close this issue for now.
